# Generated by Django 4.2.4 on 2023-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
